### ISSUE TITLE
BluetoothDevice.isServiceResolved throws DBusExecutionException

### ISSUE THREAD

**Issue by daviessm** [hypfvieh/bluez-dbus#10]
`org.freedesktop.dbus.exceptions.DBusExecutionException: No such property 'ServiceResolved' `

https://github.com/hypfvieh/bluez-dbus/blob/82bf6cff83933db3bbbbf65e69f4dc6d412ef155/src/main/java/com/github/hypfvieh/bluetooth/wrapper/BluetoothDevice.java#L253 appears to call `ServiceResolved` but the [DBus API documentation](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt) shows it's **ServicesResolved** (plural).

**Comment by hypfvieh** [comment]
Fixed in latest commit.
