### ISSUE TITLE
setTyped

### ISSUE THREAD

**Issue by MichelVos** [hypfvieh/bluez-dbus#12]
I think I found a little issue with setTyped in AbstractBluetoothObject
/**
     * Helper to set a value on a DBus property.
     *
     * @param _field DBus property key
     * @param _value value to set
     */
    protected void setTyped(String _field, Object _value) {
        try {
            Properties remoteObject = dbusConnection.getRemoteObject("org.bluez", dbusPath, Properties.class);
//            remoteObject.Set(Adapter1.class.getName(), _field, _value);
            remoteObject.Set(getInterfaceClass().getName(), _field, _value);
        } catch (DBusException _ex) {
            logger.trace("Error while setting data for DBUS (Field: {}, Value: {}).", _field, _value, _ex);
        }
    }

I think the remotObject.Set should use the getInterfaceClass().getName()

Hope this helps
Cheers
Michel Vos

**Comment by hypfvieh** [comment]
thanks
