### ISSUE TITLE
Is bluez-dbus compatible with 5.50 instead of BlueZ 5.48?

### ISSUE THREAD

**Issue by s5uishida** [hypfvieh/bluez-dbus#14]
README.md says that it was tested with BlueZ 5.48, but compared to the documentation of the interface of BlueZ, the interface class of bluez-dbus seems to correspond to 5.50 instead of 5.48.

P.S.

In dbus-java, the plan to replace JNI independent jnr-unixsocket is great!

**Comment by hypfvieh** [comment]
The current version is indeed a bit newer than the README says. 
5.46 was the version I used when starting this little project. It was later updated to 5.48 and lastly to 5.50 without mention it in README.md.
I'll fix that.

**Comment by s5uishida** [comment]
I checked it. Thank you very much.
