### ISSUE TITLE
I want getDBusConnection() I/F in DeviceManager class.

### ISSUE THREAD

**Issue by s5uishida** [hypfvieh/bluez-dbus#15]
It is useful to have getDBusConnection() I/F in the DeviceManager class.
```
    public DBusConnection getDBusConnection() {
    	return dbusConnection;
    }
```

I pass the reference of the DBusConnection instance acquired above to the first argument of DbusHelper.getRemoteObject() and use it. Specifically, I use it to obtain a reference of Device1 instance.

If there are other good ways, I would be glad if you could tell me.

P.S.

I am running a sample application on Apache Felix 6.0.3 (OSGi), but it didn't work if the bundle that loads the JNI shared library and the bundle that uses it are separated, so I use these bundles in one bundle.

- dbus-java 3.0.2
- java-utils 1.0.5

In addition, I expect that such correspondence will become unnecessary if it is changed to jnr-unixsocket from now on.

**Comment by hypfvieh** [comment]
I've added a getter.

With dbus-java 3.2.0 there will also be a osgi-bundle for dbus-java and friends. 
Maybe that helps in your case.
