### ISSUE TITLE
com.github.hypfvieh.system.NativeLibraryLoader code missed

### ISSUE THREAD

**Issue by seandu2008** [hypfvieh/bluez-dbus#2]

**Comment by hypfvieh** [comment]
A proper description would be helpful -.-

Anyway. There is no code missing. The class you mention is part of my java-utils libary which is a dependency of libmatthew, which is used to read/write unix sockets.

bluez-dbus -> dbus-java -> libmatthew -> java-utils

Please check your setup. 
May you are missing java-utils library or you have excluded a required dependency.
