### ISSUE TITLE
how to response to ATT `Handle Value Notification`

### ISSUE THREAD

**Issue by abunaiquad** [hypfvieh/bluez-dbus#43]
Hi, 

Could you please show me how to response to `Handle Value Notification` in this library?

This was extracted in btmon log.
> ACL Data RX: Handle 3 flags 0x02 dlen 9                 
      ATT: Handle Value Notification (0x1b) len 4
        Handle: 0x000f
          Data: 01ab

Thanks

**Comment by hypfvieh** [comment]
Sorry I can't help you.
The provided information is not enough.
