### ISSUE TITLE
Ability to remove property and signal handlers from the com.github.hypfvieh.bluetooth.DeviceManager

### ISSUE THREAD

**Issue by OlegAndreych** [hypfvieh/bluez-dbus#48]
I have a case when the need for subscriptions for different properties comes and goes.

As a workaround, I can have a generic subscription, which will delegate to specific handlers, relieving one from the need to register handlers in the `DeviceManager`. But having only handlers with a lifecycle tied to the objects representing devices seems more natural.

As far as I can see, underlying org.freedesktop.dbus.connections.impl.DBusConnection already has corresponding methods.

**Comment by hypfvieh** [comment]
I added methods to remove signal handlers.
But you can already do that without these methods by calling `deviceManager.getDBusConnection().removeSigHandler(class, handler)`

**Comment by OlegAndreych** [comment]
> But you can already do that without these methods by calling deviceManager.getDBusConnection().removeSigHandler(class, handler)

Thanks for the methods and the idea.
