### ISSUE TITLE
Package com.github.hypfvieh.system is missing

### ISSUE THREAD

**Issue by AlphaA841** [hypfvieh/bluez-dbus#5]
When I tried to compile bluez-dbus-master I was unable to since

package com.github.hypfvieh.system does not exist

import com.github.hypfvieh.system.NativeLibraryLoader;

bluez-dbus-master\src\main\java\com\github\hypfvieh\bluetooth\DeviceManager.java:[22,33] error: package com.github.hypfvieh.system does not exist

**Comment by hypfvieh** [comment]
You need to have the dependencies as well.
It looks like you were missing java-utils.

Source is here: https://github.com/hypfvieh/java-utils
Or use the maven dependency directly:
```
<dependency>
    <groupId>com.github.hypfvieh</groupId>
    <artifactId>java-utils</artifactId>
    <version>1.0.2</version>
</dependency>
```
Usually this artifact should be included transitive by maven:

bluez-dbus -> dbus-java -> libmatthew -> java-utils
