### ISSUE TITLE
bluez-dbus license

### ISSUE THREAD

**Issue by pierantoniomerlino** [hypfvieh/bluez-dbus#50]
What is the license of bluez-dbus?

The [license](https://github.com/hypfvieh/bluez-dbus/blob/master/LICENSE) file states that the license is MIT.
However, in the [pom.xml](https://github.com/hypfvieh/bluez-dbus/blob/master/pom.xml#L244) file and in [MVN Repository](https://mvnrepository.com/artifact/com.github.hypfvieh/bluez-dbus/0.1.3) is seems that it is LGPL.

I root for MIT :-)

**Comment by hypfvieh** [comment]
The license information in pom.xml was wrong (was copied from dbus-java on project creation).
The correct license is MIT, I fixed that in pom.xml
