### ISSUE TITLE
Create A BLE Server

### ISSUE THREAD

**Issue by ameshf** [hypfvieh/bluez-dbus#54]
Is there a way to create a BLE server on the raspberry pi with this plugin?

**Comment by hypfvieh** [comment]
I never tried or even thought about doing this.
But as this library only provides interface classes for talking to bluez using dbus, it should be possible to do so.
However I can't give you any advice on how to start. 
There are some ble-gatt-server samples written in C/C++ in the net (there is also a sample in bluez source), maybe you start investigating them.
