### ISSUE TITLE
bluez-dbus with dbus-java 3.3.2

### ISSUE THREAD

**Issue by pierantoniomerlino** [hypfvieh/bluez-dbus#55]
The last release of `bluez-dbus` (0.1.4) uses `dbus-java` with version 3.3.0. Is it possible to update the `dbus-java` to the 3.3.2 version? Are there any incompatibility?

**Comment by hypfvieh** [comment]
Using any newer version from same major branch (3.3.x) is possible and should work.
Just replace the dependency by adding the newer version and maybe exclude the one bluez-dbus wants to use.

**Comment by pierantoniomerlino** [comment]
Thanks for the fast reply!
