### ISSUE TITLE
get RSSI fail

### ISSUE THREAD

**Issue by 1784450277** [hypfvieh/bluez-dbus#59]
bluetoothDevice.getRssi()
Method threw 'org.freedesktop.dbus.exceptions.DBusExecutionException' exception.

![image](https://user-images.githubusercontent.com/44330411/229507745-cce2bd16-799e-442e-bdb3-11a073d6d017.png)

**Comment by hypfvieh** [comment]
So what do you trying to tell me?
The exception clearly says, there is no RSSI property on the device you want to query. 
Not every device supports every feature or property, so the best thing the libary can do is throwing an exception when something is not supported.

**Comment by 1784450277** [comment]
Sorry, I originally thought this attribute was present on all devices because the corresponding RSSI value can be obtained during scanning. Thank you for your reply
