### ISSUE TITLE
Bluetooth scanning can scan for devices that are turned off

### ISSUE THREAD

**Issue by 1784450277** [hypfvieh/bluez-dbus#60]
I found that when Bluetooth scans, it will scan devices that have already been turned off. Have you ever encountered this problem before? This device was previously connected by me

com.github.hypfvieh.bluetooth.DeviceManager#scanForBluetoothDevices(java.lang.String, int)

**Comment by hypfvieh** [comment]
Which devices are visible/found during scan depends on what bluez sees. 
When bluez thinks that a device is still available (even though it has been turned off) it will be found during scan.

**Comment by 1784450277** [comment]
After restarting my device, I can still scan the device that has been shut down. Where does this data exist? Is it possible for me to clear this data

**Comment by hypfvieh** [comment]
This library is only a bridge between java and bluez. It does this by providing the required interface classes used to connect to bluez using dbus.
If bluez has stored something somewhere and still propagates this information on dbus you will still get that information.

There is no way of clearing this data. This library simply uses what bluez is publishing on DBus. You may try the bluez commandline tool to check what bluez does. You may also use dbus commandline utils (or a GUI like d-feet) to see what information bluez is publishing on the bus.

**Comment by 1784450277** [comment]
I have found a solution that can clear the cache after executing a command
    service bluetooth stop
    rm -rf /var/lib/bluetooth
    service bluetooth start
