### ISSUE TITLE
Direct connection to the device by BT device address

### ISSUE THREAD

**Issue by yawor** [hypfvieh/bluez-dbus#7]
Is there any way to create a direct connection to a device with known BD address, without the need to run the discovery? From what I can see, the only way right now to get a `BluetoothDevice` object is from the `DeviceManager` is by running the discovery. If I already know the addresses of devices I need to connect to, running the discovery first seems like a unnecessary step.

**Comment by hypfvieh** [comment]
I added a new variant of method getDevices which takes a boolean to disable scanning.
It will return all bluetooth devices currently published on DBus by bluez library.

You have to look for the device you want to connect to yourself. 
Also be aware, that connection may fail if device is not in range (scanning will always make sure only devices are listed which are available).
Also it will probably only list devices which were found in a previous scan or were trusted/paired by bluez before.
